name: website-deploy

on:
  push:
    branch:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set node version 
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Check
        run: echo 'Até agora tudo filé'
      
      - name: Vite Build
        run: npm run build
